/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as privateDashboardRouteImport } from './routes/(private)/dashboard'
import { Route as landingLayoutRouteImport } from './routes/(landing)/_layout'
import { Route as privateDashboardIndexRouteImport } from './routes/(private)/dashboard/index'
import { Route as landingLayoutIndexRouteImport } from './routes/(landing)/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as landingLayoutTermsRouteImport } from './routes/(landing)/_layout/terms'
import { Route as landingLayoutPrivacyRouteImport } from './routes/(landing)/_layout/privacy'
import { Route as landingLayoutHowItsWorksRouteImport } from './routes/(landing)/_layout/how-its-works'
import { Route as landingLayoutFeaturesRouteImport } from './routes/(landing)/_layout/features'
import { Route as landingLayoutContactRouteImport } from './routes/(landing)/_layout/contact'
import { Route as landingLayoutAuthSignInRouteImport } from './routes/(landing)/_layout/auth/sign-in'

const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardRoute = privateDashboardRouteImport.update({
  id: '/(private)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const landingLayoutRoute = landingLayoutRouteImport.update({
  id: '/(landing)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardIndexRoute = privateDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateDashboardRoute,
} as any)
const landingLayoutIndexRoute = landingLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const landingLayoutTermsRoute = landingLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => landingLayoutRoute,
} as any)
const landingLayoutPrivacyRoute = landingLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => landingLayoutRoute,
} as any)
const landingLayoutHowItsWorksRoute =
  landingLayoutHowItsWorksRouteImport.update({
    id: '/how-its-works',
    path: '/how-its-works',
    getParentRoute: () => landingLayoutRoute,
  } as any)
const landingLayoutFeaturesRoute = landingLayoutFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => landingLayoutRoute,
} as any)
const landingLayoutContactRoute = landingLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => landingLayoutRoute,
} as any)
const landingLayoutAuthSignInRoute = landingLayoutAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => landingLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof privateDashboardRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/contact': typeof landingLayoutContactRoute
  '/features': typeof landingLayoutFeaturesRoute
  '/how-its-works': typeof landingLayoutHowItsWorksRoute
  '/privacy': typeof landingLayoutPrivacyRoute
  '/terms': typeof landingLayoutTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof landingLayoutIndexRoute
  '/dashboard/': typeof privateDashboardIndexRoute
  '/auth/sign-in': typeof landingLayoutAuthSignInRoute
}
export interface FileRoutesByTo {
  '/r/$slug': typeof RSlugRoute
  '/contact': typeof landingLayoutContactRoute
  '/features': typeof landingLayoutFeaturesRoute
  '/how-its-works': typeof landingLayoutHowItsWorksRoute
  '/privacy': typeof landingLayoutPrivacyRoute
  '/terms': typeof landingLayoutTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof landingLayoutIndexRoute
  '/dashboard': typeof privateDashboardIndexRoute
  '/auth/sign-in': typeof landingLayoutAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(landing)/_layout': typeof landingLayoutRouteWithChildren
  '/(private)/dashboard': typeof privateDashboardRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/(landing)/_layout/contact': typeof landingLayoutContactRoute
  '/(landing)/_layout/features': typeof landingLayoutFeaturesRoute
  '/(landing)/_layout/how-its-works': typeof landingLayoutHowItsWorksRoute
  '/(landing)/_layout/privacy': typeof landingLayoutPrivacyRoute
  '/(landing)/_layout/terms': typeof landingLayoutTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(landing)/_layout/': typeof landingLayoutIndexRoute
  '/(private)/dashboard/': typeof privateDashboardIndexRoute
  '/(landing)/_layout/auth/sign-in': typeof landingLayoutAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/r/$slug'
    | '/contact'
    | '/features'
    | '/how-its-works'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/'
    | '/dashboard/'
    | '/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/r/$slug'
    | '/contact'
    | '/features'
    | '/how-its-works'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
  id:
    | '__root__'
    | '/(landing)/_layout'
    | '/(private)/dashboard'
    | '/r/$slug'
    | '/(landing)/_layout/contact'
    | '/(landing)/_layout/features'
    | '/(landing)/_layout/how-its-works'
    | '/(landing)/_layout/privacy'
    | '/(landing)/_layout/terms'
    | '/api/auth/$'
    | '/(landing)/_layout/'
    | '/(private)/dashboard/'
    | '/(landing)/_layout/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  landingLayoutRoute: typeof landingLayoutRouteWithChildren
  privateDashboardRoute: typeof privateDashboardRouteWithChildren
  RSlugRoute: typeof RSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/dashboard': {
      id: '/(private)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/_layout': {
      id: '/(landing)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof landingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/dashboard/': {
      id: '/(private)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof privateDashboardIndexRouteImport
      parentRoute: typeof privateDashboardRoute
    }
    '/(landing)/_layout/': {
      id: '/(landing)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingLayoutIndexRouteImport
      parentRoute: typeof landingLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/_layout/terms': {
      id: '/(landing)/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof landingLayoutTermsRouteImport
      parentRoute: typeof landingLayoutRoute
    }
    '/(landing)/_layout/privacy': {
      id: '/(landing)/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof landingLayoutPrivacyRouteImport
      parentRoute: typeof landingLayoutRoute
    }
    '/(landing)/_layout/how-its-works': {
      id: '/(landing)/_layout/how-its-works'
      path: '/how-its-works'
      fullPath: '/how-its-works'
      preLoaderRoute: typeof landingLayoutHowItsWorksRouteImport
      parentRoute: typeof landingLayoutRoute
    }
    '/(landing)/_layout/features': {
      id: '/(landing)/_layout/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof landingLayoutFeaturesRouteImport
      parentRoute: typeof landingLayoutRoute
    }
    '/(landing)/_layout/contact': {
      id: '/(landing)/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof landingLayoutContactRouteImport
      parentRoute: typeof landingLayoutRoute
    }
    '/(landing)/_layout/auth/sign-in': {
      id: '/(landing)/_layout/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof landingLayoutAuthSignInRouteImport
      parentRoute: typeof landingLayoutRoute
    }
  }
}

interface landingLayoutRouteChildren {
  landingLayoutContactRoute: typeof landingLayoutContactRoute
  landingLayoutFeaturesRoute: typeof landingLayoutFeaturesRoute
  landingLayoutHowItsWorksRoute: typeof landingLayoutHowItsWorksRoute
  landingLayoutPrivacyRoute: typeof landingLayoutPrivacyRoute
  landingLayoutTermsRoute: typeof landingLayoutTermsRoute
  landingLayoutIndexRoute: typeof landingLayoutIndexRoute
  landingLayoutAuthSignInRoute: typeof landingLayoutAuthSignInRoute
}

const landingLayoutRouteChildren: landingLayoutRouteChildren = {
  landingLayoutContactRoute: landingLayoutContactRoute,
  landingLayoutFeaturesRoute: landingLayoutFeaturesRoute,
  landingLayoutHowItsWorksRoute: landingLayoutHowItsWorksRoute,
  landingLayoutPrivacyRoute: landingLayoutPrivacyRoute,
  landingLayoutTermsRoute: landingLayoutTermsRoute,
  landingLayoutIndexRoute: landingLayoutIndexRoute,
  landingLayoutAuthSignInRoute: landingLayoutAuthSignInRoute,
}

const landingLayoutRouteWithChildren = landingLayoutRoute._addFileChildren(
  landingLayoutRouteChildren,
)

interface privateDashboardRouteChildren {
  privateDashboardIndexRoute: typeof privateDashboardIndexRoute
}

const privateDashboardRouteChildren: privateDashboardRouteChildren = {
  privateDashboardIndexRoute: privateDashboardIndexRoute,
}

const privateDashboardRouteWithChildren =
  privateDashboardRoute._addFileChildren(privateDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  landingLayoutRoute: landingLayoutRouteWithChildren,
  privateDashboardRoute: privateDashboardRouteWithChildren,
  RSlugRoute: RSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
